### ISSUE TITLE
Improve Civiform deployment dev documentation

### ISSUE THREAD

**Issue by jessbumblebee** [civiform/civiform#4324] opened 2023-03-06 12:13 UTC
The developer docs for deployment contributions are very sparse at the moment. 
Some suggestions for improvments are here:

https://docs.google.com/document/d/1TpPsGR8hydYae2J2W-pC0tYX_J5k7g6mU8ztR1o9MDU/edit

**Comment by rockycodes** [comment] 2024-01-30 21:49
closing as a duplicate of https://github.com/civiform/civiform/issues/5250

**Closed by rockycodes** 2024-01-30 21:49 UTC
Labels: documentation, technical-writing, deploy, cleanup
