### ISSUE TITLE
Application progress indicator text is not localized

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3578] opened 2022-09-29 16:33 UTC
We indicate progress within the application in the UI on the block editing pages:
![Screen Shot 2022-09-29 at 9 32 03 AM](https://user-images.githubusercontent.com/1870301/193087911-c47774e3-44dd-449a-a4ca-6c4b79ab6560.png)

This text is not localized. Additionally, we use the progress as part of the page titles for block editing, application preview, and application review pages. We should add localization for these strings.

**Comment by cassandralfernandes** [comment] 2022-09-29 17:17
Duplicate of #3068

**Closed by cassandralfernandes** 2022-09-29 17:17 UTC
Labels: bug, needs-triage
