### ISSUE TITLE
Switching language in middle of application navigates to 404 page

### ISSUE THREAD

**Issue by leonwong** [civiform/civiform#1576] opened 2021-08-10 20:20 UTC
**Describe the bug**
In the middle of the application, if you switch languages, the browser navigates to a URL that does not seem to exist.

**To Reproduce**
1. Apply for ORCA program
1. Fill out some questions
1. Attempt to submit a screen with missing answers
1. See validation error message
1. Switch languages using the picker at the top of the screen 

**Expected behavior**
Expect language to switch successfully (even if not all strings have been translated this should be best effort).

**Screenshots**
<img width="1030" alt="Screen Shot 2021-08-10 at 1 16 21 PM" src="https://user-images.githubusercontent.com/926911/128929257-b2f00e41-4776-4eb0-aca7-096659f47c2c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by leonwong** [comment] 2021-08-10 20:32
I think this only happens if you tried to submit with unanswered required questions.

**Comment by reemaka** [comment] 2023-04-21 20:12
can't reproduce this anymore

**Comment by reemaka** [comment] 2023-04-21 20:14
jk, was able to reproduce this immediately after i closed this

**Closed** 2024-07-22 20:42 UTC
Labels: bug
