### ISSUE TITLE
[North Star Applicant UI] Designs for duplicate submission page

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7905] opened 2024-06-26 21:30 UTC
See https://github.com/civiform/civiform/issues/7875 for what the page looks like now.

This page is shown when the user submits an application, goes to edit it, and submits without making any changes.

**Comment by ssandbekkhaug** [comment] 2024-07-09 17:35
Duplicate of #7987

**Closed by ssandbekkhaug** 2024-07-09 17:35 UTC
Labels: UX, [Epic] North Star Applicant UI
