### ISSUE TITLE
Write pg_access script for AWS

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#3504] opened 2022-09-26 18:21 UTC
After [#2563](https://github.com/civiform/civiform/issues/2563) is complete - write scripts to access db and add make sure they are accessible from https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/bin/run.py

**Comment by avrittrohwer** [comment] 2022-11-08 18:47
Duplicate of https://github.com/civiform/civiform/issues/2563

**Closed** 2022-11-08 18:47 UTC
Labels: deploy
