### ISSUE TITLE
Only allow an applicant to submit one application to a program

### ISSUE THREAD

**Issue by lindsayzad** [civiform/civiform#1569] opened 2021-08-10 18:44 UTC
**Describe the bug**
Users can submit their application to a program multiple times with no limit.  This is a possible avenue of abuse for malicious users, and is also confusing for benevolent users. 

**To Reproduce**

1. Go to a program
2. Fill out all of the questions
3. Click 'Submit'
4. Navigate back to the program
5. Be brought back directly to the ending review screen
6. Click 'Submit' again
7. Repeat Steps 4-6 ad nauseam

Or:
1. Go to a program
2. Fill out all of the questions
3. Click 'Submit'
4. Click 'Back'
5. See the ending review screen
6. Click 'Submit' again
7. Repeat Steps 4-6 ad nauseam

**Expected behavior**
A user should only be able to apply to a specified program once.

**Additional context**
Related issue #850

**Comment by reemaka** [comment] 2023-06-27 15:05
Duplicate of #4869

**Closed** 2023-08-24 18:26 UTC
Labels: bug
