### ISSUE TITLE
Increase Observability Capabilities

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3244] opened 2022-08-24 00:00 UTC
### Epic Overview
 Monitoring & Observability
### Problem Statements(s)
CiviForm is missing the kind of instrumentation and data presentation that makes maintaining and operating a web service less risky (i.e. observability or o11y). Entities have little more than server logs with the basic cloud-provider provided tools for searching through them. Looking through logs is onerous, and looking into critical metrics such as QPS, request latency, error ratios, etc is impossible.

Improving this circumstance is made more complicated since we cannot mandate a specific paid tool for civic entities to use for o11y. There are however open-source instrumentation tools that allow the implementer to choose their own paid data ingestion and presentation service. https://micrometer.io/ is one such example.

From @shanemc-goog:

Likewise the ability to launch new features an observe they're working as intended is missing.

We currently launch features with code pushes, so the lack of observability makes it hard to do this safely, or know if a rollback is needed.

### Product Requirements
n/a

### Design & Eng Requirements
link + any important details

**Comment by bion** [comment] 2022-09-06 19:03
duplicate of https://github.com/civiform/civiform/issues/3244

**Closed by bion** 2022-09-06 19:03 UTC

**Comment by cassandralfernandes** [comment] 2022-09-30 22:33
@bion for roadmapping and stakeholder reporting purposes, would you mind adding a high-level update of the Q3 progress we made on this epic under "End of Quarter 3 Update" and note which parts of this work will continue in Q4? 

I am going to leave this issue on the roadmap for Q3. I renamed #1974 and added it to the roadmap for Q4. Let me know if any of this doesn't make sense --  Github is a bit wacky about how this roadmap stuff shows up, as you know
