### ISSUE TITLE
Use consistent copy text casing throughout app

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1401] opened 2021-06-21 21:56 UTC
We use a mix of Sentence Case, Title case, and ALL CAPS throughout CiviForm, with inconsistent patterns. See this example from the program builder:

![image](https://user-images.githubusercontent.com/77128518/122831455-c2cfdc00-d29e-11eb-97f4-2f23af578355.png)

We should settle on, implement, and document a consistent casing pattern, such as:

- ALL CAPS for buttons
- Title Case for tabs, menu items, and headings
- Sentence case for the rest

We can change up the policy above, as long as we're consistent with it.

**Comment by nbeloglazov** [comment] 2022-07-07 23:11
Is this bug a duplicate of #1250 or probably superset?

**Closed** 2023-04-12 19:27 UTC
Labels: good first issue, technical-writing
