### ISSUE TITLE
Program Summary Cards - overflow text causing scrolling

### ISSUE THREAD

**Issue by paripatel07** [civiform/civiform#5942] opened 2023-11-07 21:05 UTC
**Describe the bug**
The program summary cards on the main page sometimes are scrollable when there is too much text

**To Reproduce**
See screenshot of example

**Expected behavior**
Potential Options:
1. Add max character length for admins
2. Enable auto height on cards based on content
3. Add "read more" option so it only expands when user clicks on that button

**Screenshots**
[Link](https://docs.google.com/document/d/1fI3dUGXR_1mAF53cg1gxOxIS0UT1SetyZHo2h7nG-gQ/edit?resourcekey=0-JidKSEZBcXLhgvBgn_UugQ)

**Comment by rockycodes** [comment] 2023-11-07 22:10
I was just looking at this today. The program cards are set up so when [you click on them it removes the "line clamp"](https://github.com/civiform/civiform/blob/32bc2499819f2986eb15db46a31bfc7bc4a1cb18/server/app/assets/javascripts/main.ts#L216) and the full program description is viewable/scrollable. Based on the comment in the code, this was meant to be a temporary fix.

**Comment by gwendolyngoetz** [comment] 2024-01-18 22:49
https://github.com/civiform/civiform/issues/6404

**Comment by caitlinshk** [comment] 2024-02-29 20:14
Duplicate of #6404

**Closed by caitlinshk** 2024-02-29 20:14 UTC
Labels: bug, UX, needs-triage
