### ISSUE TITLE
File upload focus

### ISSUE THREAD

**Issue by shreyachatterjee00** [civiform/civiform#9390] opened 2024-12-04 21:03 UTC
With a file input question, after uploading the file, focus jumps to the top of the page.
Video here: https://civiform.slack.com/files/U057V0H2K0W/F083RP4MPSQ/screen_recording_2024-12-04_at_10.22.05___am.mov

**Comment by melanie-exygy** [comment] 2024-12-05 21:32
This is a duplicate of #8719.

**Closed by melanie-exygy** 2024-12-05 21:32 UTC
Labels: bug, [Epic] North Star Applicant UI
