### ISSUE TITLE
Published forms aren't in chronological order

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#1649] opened 2021-10-20 16:37 UTC
**Describe the bug**
Program admins are able to view previously published forms and the applications that were submitted under those forms. The published forms aren't in chronological order though, so it makes it hard for admins to see which one is the most recent past version. 

**To Reproduce**
1. Login as a program admin
2. Scroll down to see applications submitted by form #
3. See the past forms in random order

**Expected behavior**
Past published forms should show in chronological order of when they were originally published.

**Screenshots**
I'll add screenshots once CiviForm is up and running

**Comment by ettengererin** [comment] 2021-11-01 18:21
@elisekalstad I wasn't able to reproduce this issue. Can you please add screenshots if you have any?

**Comment by elisekalstad** [comment] 2021-11-01 18:28
![Form Version Issue](https://user-images.githubusercontent.com/86082659/139722112-7ee8ae65-f933-437a-b43e-4dce19a9eff6.jpg)

**Comment by elisekalstad** [comment] 2021-11-01 18:28
> @elisekalstad I wasn't able to reproduce this issue. Can you please add screenshots if you have any?

Yes! Sorry about that!

**Comment by bion** [comment] 2022-12-01 18:17
closing as duplicate of https://github.com/civiform/civiform/issues/3782

**Closed by bion** 2022-12-01 18:17 UTC
Labels: bug, good first issue, admin-ui
