### ISSUE TITLE
Add graphics and icons on applicant homepage to make programs easier to find

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1494] opened 2021-06-25 17:30 UTC
Especially once we have a lot of programs on CiviForm, it'll become hard to scan the page to find programs that an applicant needs.

One of the great things that [affordableseattle.org](https://affordableseattle.org) does is adding images to each program's card, plus adding icons for different categories of programs. This makes it easy for applicants (especially those with limited literacy) to scan the list and pick out what they need.

![image](https://user-images.githubusercontent.com/77128518/123463502-73d8be00-d5a0-11eb-8b3d-f456b38bdefa.png)

This was *very* common user feedback that we got from CBOs.

We also need to add a place for CiviForm admins to specify the category of a program and the cover photo. Perhaps on the program details editing page.

![image](https://user-images.githubusercontent.com/77128518/123463459-67546580-d5a0-11eb-984e-6e8ee998e08d.png)

**Comment by Carolina-start** [comment] 2021-06-26 00:08
@neel-a-mehta I want to work in this one too!

**Comment by baipai** [comment] 2021-06-26 07:42
Hi, @Carolina-start I made this part a very long time ago, I will post this one in the figma and share it with you here.

**Comment by Carolina-start** [comment] 2021-07-19 22:45
what information do they need to include in the data? #of applicants? # programs? demographics?

**Comment by Carolina-start** [comment] 2021-07-19 22:47
> Hi, @Carolina-start I made this part a very long time ago, I will post this one in the figma and share it with you here.

Please @baipai can you share the link, so I can take a quick view of that part

**Comment by baipai** [comment] 2021-07-20 00:07
@Carolina-start 
I will do it today, and actually cleaning up the old figma file is the first priority rather than creating the new one for now. 

Please move your TI design into the page that Holly mentioned in the post if you haven't done it. Because she will need to present it this week or next week and this is the most important thing right now.

**Comment by elisekalstad** [comment] 2022-11-14 23:12
I don't believe this is actually done. There is a duplicate here: https://github.com/civiform/civiform/issues/3783

**Comment by bion** [comment] 2023-07-13 22:28
duplicate of https://github.com/civiform/civiform/issues/3783

**Closed by bion** 2023-07-13 22:28 UTC
Labels: story, user-feedback, a11y, seattle, enhancement
