### ISSUE TITLE
"Smart" Program Discovery

### ISSUE THREAD

**Issue by kristinyim** [civiform/civiform#1925] opened 2022-02-11 23:54 UTC
**PROBLEM:**
Residents want to be able to better understand what programs their cities offer and which ones they are eligible for

**SOLUTION:**
We could potentially do this in a "smart" way, like after they've submitted an application, suggesting other programs immediately -- or following up via email

**Comment by rasmi** [comment] 2023-05-26 17:15
Closed as duplicate of #4714

**Closed by rasmi** 2023-05-26 17:15 UTC
Labels: feature
