### ISSUE TITLE
Connect a JS widget that validates whether the address supplied is valid

### ISSUE THREAD

**Issue by lindsayzad** [civiform/civiform#1571] opened 2021-08-10 18:55 UTC
**Is your feature request related to a problem? Please describe.**
Currently, applicants can supply any address in the form, even if it is completely fake.  

**Describe the solution you'd like**
We should attach a widget, perhaps through Google Maps, that validates whether the address that is supplied by the applicant is indeed a valid address

**Done when**
Fake addresses are not accepted, but no valid addresses are turned away

**Comment by bion** [comment] 2021-08-11 17:21
Duplicate of https://github.com/seattle-uat/civiform/issues/428

**Closed** 2023-07-18 17:30 UTC
Labels: feature
