### ISSUE TITLE
Run probers on Azure staging periodically

### ISSUE THREAD

**Issue by bion** [civiform/civiform#2233] opened 2022-03-30 23:17 UTC
Run the browser test suite against staging on each deploy and report failure somewhere visible.

Some code paths cannot be exercised in dev and test environments so this gives us much more confidence that a build is good to release to production.

**Comment by azizova-leyla** [comment] 2022-09-16 15:59
Duplicate of https://github.com/civiform/civiform/issues/2541

**Closed** 2022-09-16 15:59 UTC
Labels: testing, tech-debt
