### ISSUE TITLE
[North Star Applicant UI] Add styles to review/summary page

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7687] opened 2024-06-05 21:20 UTC
Add styles to the review page when specs are available

**Comment by ssandbekkhaug** [comment] 2024-10-03 19:14
Blocked on [#7935](https://github.com/civiform/civiform/issues/7935) but Sijia mentioned the mocks should be ready today

**Comment by ssandbekkhaug** [comment] 2024-10-04 16:06
Duplicate of #8794

**Closed by ssandbekkhaug** 2024-10-04 16:06 UTC
Labels: UX, [Epic] North Star Applicant UI
