### ISSUE TITLE
Applicant PDF download after applying to a program with file upload question includes a link to download file that doesn't work

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#7205] opened 2024-04-11 16:02 UTC
**Describe the bug**
When APPLICATION_EXPORTABLE flag is turned on (on the settings page), applicants are able to download a PDF of their application after submitting. If the program includes a file upload question, there will be a link to download the file in the PDF, but this doesn't work. We should change the behavior.

Note that the full link (https://staging-aws.civiform.dev/applicants/726268/files/applicant-726268%252Fprogram-108036%252Fblock-1%252Fcharlotte+%25281%2529+%25282%2529.jpg) will work if you're already logged in, but it won't otherwise. 

We'll plan to go with the option below, which involves downloading the uploaded files when exporting the application and changing the name in the export to be: `(PDF downloaded separately)` from `UPLOADED (click to download)` and removing the link property of the text

**To Reproduce**

1. Create an application with a file upload question
2. As an admin turn on APPLICATION_EXPORTABLE
3. Login as an applicant and fill out the application and export the PDF at the end
4. Click the download link in the PDF
5. Get navigated to home page

**Expected behavior**
Download the uploaded files when exporting the application and changing the name in the export to be: `(PDF downloaded separately)` from `UPLOADED (click to download)`. The text should no longer be clickable as well.

**Screenshots**
[name-unavailable (79548)-2024-04-11T08_37_10.198442.pdf](https://github.com/civiform/civiform/files/14948474/name-unavailable.79548.-2024-04-11T08_37_10.198442.pdf)

**Additional context**
See https://github.com/civiform/civiform/issues/7149 for further context

**Comment by shreyachatterjee00** [comment] 2024-04-11 21:00
@dkatzz I think it's fine to add a link to the review page and say something like "Go to the application review page to download this file: [LINK]" 

Though if the applicant is not logged in, wouldn't this link still redirect them to the homepage?

**Comment by dkatzz** [comment] 2024-04-11 21:38
> @dkatzz I think it's fine to add a link to the review page and say something like "Go to the application review page to download this file: [LINK]"
> 
> Though if the applicant is not logged in, wouldn't this link still redirect them to the homepage?

Yeah it would - could also just include that message without the link? Lmk what you think!

**Comment by sijiayam** [comment] 2024-04-11 22:39
@dkatzz Is there the ability to append the document they uploaded to the download file?

**Comment by dkatzz** [comment] 2024-04-11 23:09
> @dkatzz Thinking of ways to create a seamless experience:

Thank you!!
> 
> * Is there the ability to append the document they uploaded to the download file?

I'll look into that - unfortunately I think it may be a bit more difficult because we get the file from AWS S3 (file storage system) so we basically check if they have permissions to view that other file then do a redirect to download it from S3 directly.

> * Or would we be able to detect if there is a downloadable document and give them a link to open both links (thus downloaded both files?)

This would be easier to do! It wouldn't be a link, but when they click to download the PDF, we can have it download the two separate PDFs I think. If we do that, we can change the message in the first export from `Sample File Upload Question
-- charlotte (1) (2).jpg UPLOADED (click to download) --` to `Sample File Upload Question
-- charlotte (1) (2).jpg (PDF downloaded separately)` or something else to indicate it can also be viewed on the review page (https://staging-aws.civiform.dev/programs/108467/review)

<img width="1181" alt="Screenshot 2024-04-11 at 7 05 28 PM" src="https://github.com/civiform/civiform/assets/86739416/d83e623a-61dd-4620-ba8c-da6de2cf5f27">

Let me know what you think

**Comment by dkatzz** [comment] 2024-04-19 21:12
We can also just remove the `(click to download)` part in the meantime while we figure out what we should do. Either that or add `(download on review page)` or something. Let me know what you think @sijiayam !

**Comment by sijiayam** [comment] 2024-04-22 19:24
I like the later option you mentioned on downloading two separate PDFs when they click on the link! @dkatzz

**Comment by devin-civi** [comment] 2024-05-09 18:26
I've got a fix pending for this issue, but it's different than discussed above because the root cause was also different than we'd guessed. The root cause of the problem was we were putting the admin link to view the document in, rather than the applicant link, so it'd fail whether you were logged in. My change fixes that, so logged in applicants can download their uploaded files from a PDF.

We'll still get the problem that if you're not logged in, it will fail, so there are further improvements we could make, in particular:

1) We could prompt for a login and then continue with the download. Although that wouldn't work for guests.
2) As discussed we could try to download all the uploaded files with the application, but a single click can only download a single file, so we'd have to bundle them together, for example in a .zip file, which could be confusing to applicants.

I propose we close this once the fix goes in, and we can open another issue if there are problems.

**Comment by dkatzz** [comment] 2024-05-09 18:32
> I've got a fix pending for this issue, but it's different than discussed above because the root cause was also different than we'd guessed. The root cause of the problem was we were putting the admin link to view the document in, rather than the applicant link, so it'd fail whether you were logged in. My change fixes that, so logged in applicants can download their uploaded files from a PDF.
> 
> We'll still get the problem that if you're not logged in, it will fail, so there are further improvements we could make, in particular:
> 
> 1. We could prompt for a login and then continue with the download. Although that wouldn't work for guests.
> 2. As discussed we could try to download all the uploaded files with the application, but a single click can only download a single file, so we'd have to bundle them together, for example in a .zip file, which could be confusing to applicants.
> 
> I propose we close this once the fix goes in, and we can open another issue if there are problems.

Thank you, Devin!! That proposal SGTM! @sijiayam FYI - if we want to go with option 1 or 2 we can create a separate issue to track that.

**Closed** 2024-05-09 21:22 UTC
Labels: bug, Bloomington
