### ISSUE TITLE
Enable non-CiviForm admins to propose draft changes to questions and programs

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4870] opened 2023-05-16 18:43 UTC
**Is your feature request related to a problem? Please describe.**
Those with programs that want to put them on CiviForm don't have a structured way to get their programs on CiviForm. They would have to contact the CiviForm Admin to do so.

**Describe the solution you'd like**
Step 1: an interest form (likely Google Form) that is linked in the CiviForm portal for individuals to contact the CiviForm Admins
Step 2:  program admins should be able to propose but not finalize a program that they want to publish on CiviForm. They can see the full question bank. CiviForm Admins will make the final decision on these.

**Additional context**
AR is interested in this feature.

**Done when**
Above.

**Comment by bion** [comment] 2023-05-17 17:13
@michaelzetune should this have the `arkansas` label?

**Comment by michaelzetune** [comment] 2023-05-17 17:30
> @michaelzetune should this have the `arkansas` label?

Done thanks!

**Comment by rasmi** [comment] 2023-05-31 19:18
Closed as duplicate of #869.

**Closed by rasmi** 2023-05-31 19:18 UTC
Labels: feature, needs-triage, arkansas
