### ISSUE TITLE
Status window appears at bottom of screen

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5115] opened 2023-06-16 22:30 UTC
**Describe the bug**
As a Program Admin when I view an application and change the application status, the Status Window appears at the bottom of the screen and I need to scroll to be able to view it.

**To Reproduce**

1. Log in as a Program Admin
2. Select program
3. View application
4. Change status
5. See that the status pop-up window appears at the bottom of the page and you must scroll to send the status message.

**Expected behavior**
I would expect the Status Window to appear just below the applicant's name and the status drop-down field.

**Screenshots**
Highlighted in yellow is the current experience. I would expect to see the status pop-up window in the gray outlined area (or close to it!)

![image](https://github.com/civiform/civiform/assets/86082659/b6b83474-84c2-4c6c-b663-b39cc6b4e0b4)

**Comment by azhangggggg** [comment] 2023-12-20 22:45
I think the screenshot with this issue is outdated (which is totally understandable given this issue was filed back in June). Below is the latest one from my side. The pop-up window is now showing up in the middle of the screen. Is this expected behavior or would you still like the window to be at the top of the screen? @elisekalstad

<img width="1307" alt="Screenshot 2023-12-20 at 2 43 26 PM" src="https://github.com/civiform/civiform/assets/149536150/289d411d-4737-4dc8-a11e-9baf45344e59">

**Comment by azhangggggg** [comment] 2023-12-20 23:00
Closing this since it's no longer needed. - confirmed with the reporter over Slack.

**Comment by elisekalstad** [comment] 2024-08-30 17:39
The status is showing at the bottom of the screen again. Is it possible to align the status box with the top of the application, just below the status drop down?

![image](https://github.com/user-attachments/assets/0abc7361-6ea9-47e1-aa15-89c0b96e43ea)

**Comment by elisekalstad** [comment] 2024-08-30 17:40
Reopening for fix

**Closed** 2024-09-03 16:18 UTC
Labels: bug, google.org-swe
