### ISSUE TITLE
[PRD] Program Category Filtering

### ISSUE THREAD

**Issue by shreyachatterjee00** [civiform/civiform#5685] opened 2023-09-27 23:11 UTC
https://docs.google.com/document/d/1N7lc64XmScGxdtJVM5RyfeW3l-xQYMSdmkKSxsjTEeo/edit

Currently working on scoping the PRD for MVP of discoverability efforts in Q4.

**Comment by melanie-exygy** [comment] 2024-05-31 22:55
Closing since this is a duplicate of #7260

**Closed by melanie-exygy** 2024-05-31 22:55 UTC
Labels: PRD
