### ISSUE TITLE
Ability to embed links

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3965] opened 2022-12-19 20:55 UTC
**Is your feature request related to a problem? Please describe.**
Many programs would like to reference another website for additional information. Currently there is no way to embed urls into the question text. I can use the full URL and it is formatted beautifully as an external link. But it would be helpful to have an option of embedding the URLs as well--to cut down on text, especially if it's a long URL.

**Describe the solution you'd like**
It would be helpful if an applicant could see that a word/words within a question are formatted as a clickable link; i.e. blue text, underlined, and when clicked, it opens the external link in a new tab.

**Done when**
As a CiviForm Admin, I can specific which text should be used for an embedded link. As a resident, I should be able to click on the blue, underlined text to navigate to an external link.

For example:
Question text: "Questions? Please visit [our website](https://www.seattlefreshbucks.org/) and read our [FAQ](https://www.seattlefreshbucks.org/faq/)."

**Additional context**
This is connected to: https://github.com/civiform/civiform/issues/888

**Comment by msprenke** [comment] 2023-01-05 17:10
I tried adding some html code to the question: <a href="https://www.seattlefreshbucks.org/faq/" rel="nofollow">FAQ</a> 
This did not work.  It published exactly as seen above.

@elisekalstad would this be required in all question types?

**Comment by elisekalstad** [comment] 2023-01-05 17:19
@msprenke Ideally, yes!

**Comment by msprenke** [comment] 2023-01-17 21:17
This is a duplicate of https://github.com/civiform/civiform/issues/888 for using rich test in question descriptions in order to embed links

**Closed by msprenke** 2023-01-17 21:17 UTC
Labels: seattle, seattle-review
