### ISSUE TITLE
Program Admins/Applicants are Unable to Download Applicant Uploads

### ISSUE THREAD

**Issue by jhvhs-bloom** [civiform/civiform#7149] opened 2024-04-05 17:07 UTC
Program admins (and Applicants) accessing applicant documents are not redirected to the S3 bucket, which prevents Program admins from downloading or accessing applicant uploads. Despite, Applicant uploads successfully posting and appearing in the S3 bucket.

When Program admins 'click to download', it's a blank page and a 401 error is logged in the console. This occurs on our prod (v1.56.1) and test (v1.57.0) instances.

Could this be an issue with our S3 bucket configuration or a possible feature flag I have overlooked or a bug?

- OS: MacOS
- Browser: Firefox
- Version: 124.0.2
And
- OS: Windows 11
- Browser: Chromium

![click-to-download-401](https://github.com/civiform/civiform/assets/121638765/ddf017c2-5535-4e0b-ac7a-91ef0116d5ff)

**Comment by dkatzz** [comment] 2024-04-09 19:55
Thanks for reporting this, @jhvhs-bloom. Does switching to a prior version fix the issue? We haven't been able to reproduce, but taking a look on our side to see what could have caused this. It may be easiest to hop on a call and take a look at the S3 configuration to debug the issue if that works for you? Thanks!

**Comment by jhvhs-bloom** [comment] 2024-04-09 20:20
Thank you! It is possible for us to spin up a third environment to try a prior version. You can reach me at jeremy.schneider@bloomington.in.gov to schedule a meeting.

**Comment by dkatzz** [comment] 2024-04-10 21:04
In our meeting we found the following:

- CiviForm admins that are allowed to review programs through the ALLOW_CIVIFORM_ADMIN_ACCESS_PROGRAMS flag, are not able to download files from programs
  - Note that regular program admins do not have this issue and are able to download files as expected
  - During [this check](https://github.com/civiform/civiform/blob/9c10f19ab2f18824dd07caa54a6d441a8fcbd7b9/server/app/controllers/FileController.java#L120) we don't check if the user is a global admin like we do [here](https://github.com/civiform/civiform/blob/9c10f19ab2f18824dd07caa54a6d441a8fcbd7b9/server/app/auth/CiviFormProfile.java#L279-L282)
  - Our demo environments add ACLs to all programs, so we can't reproduce this in those environments (but we should make this line up better)
- Applicants aren't able to download a file from the PDF when clicking "View " (Note that APPLICATION_EXPORTABLE flag is needed to see this functionality).
  - Applicants are able to download their files from the review page of the application

We'll file bugs for these issues with all the related details.

**Comment by dkatzz** [comment] 2024-04-16 19:05
FYI @jhvhs-bloom the first part of the bug (CiviForm admins with access to programs are not able to download files from applications) is now fixed in the latest release ([1.60.0](https://github.com/civiform/civiform/releases/tag/v1.60.0)).

**Comment by dkatzz** [comment] 2024-04-30 14:40
@jhvhs-bloom I'll close this issue and tracking the PDF export bug in https://github.com/civiform/civiform/issues/7205. Let me know if you have any questions. Thanks!

**Closed by dkatzz** 2024-04-30 14:40 UTC
Labels: bug, Bloomington

**Comment by dkatzz** [comment] 2024-05-15 17:32
@jhvhs-bloom FYI @devin-civi fixed the PDF export bug in https://github.com/civiform/civiform/issues/7205, which is included in the [v2.0.0 release](https://github.com/civiform/civiform/releases/tag/v2.0.0). Let us know if you have any questions!
