### ISSUE TITLE
Add ability for Admins to view a published Program

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#2113] opened 2022-03-23 14:26 UTC
There is no way for an Admin to view a published Program.  The only way to see the configuration is to create a new draft version.

Questions do have a view ability.

**Comment by nbeloglazov** [comment] 2022-10-01 00:56
I believe #3162 is a newer duplicate of this one. The latter has TODOs in code so I'll close this one in favor of the other bug.

**Closed by nbeloglazov** 2022-10-01 00:56 UTC
Labels: admin-ui
