### ISSUE TITLE
Error when advancing to next screen in application

### ISSUE THREAD

**Issue by rasmi** [civiform/civiform#4944] opened 2023-05-24 15:07 UTC
From @sophiatareen:
**Describe the bug**
Error when advancing to the next screen after filling out information as a TI in a demo/staging environment.

**To Reproduce**
1. Log in as a TI
2. Go to existing client with previously entered data (e.g. Soph Ta)
3. Start Rental Assistance Program, screen 1
4. Enter requested data (e.g. DOB, Address); Save and next

**Expected behavior**
CiviForm advances to the next screen. Instead, an error is shown (see below):

![unnamed](https://github.com/civiform/civiform/assets/2267370/ee12eb4e-746a-4bb7-89a9-80088664bb1f)

Stack trace from logs:
```
[[31merror[0m] p.h.DefaultHttpErrorHandler - 
```

```
! @81k9do3g8 - Internal server error, for (GET) [/applicants/2554/programs/27/review] ->
```

```
play.api.UnexpectedException: Unexpected exception[NoSuchElementException: No value present]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
	at controllers.ErrorHandler.onServerError(ErrorHandler.java:102)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
```

```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at controllers.applicant.ApplicantProgramReviewController.review(ApplicantProgramReviewController.java:82)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$266(Routes.scala:3533)
	at play.core.routing.HandlerInvokerFactory$$anon$9.resultCall(HandlerInvoker.scala:154)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:119)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:175)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
	at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:231)
	at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522)

```

Screenshot of logging events:

![Screenshot 2023-05-24 17 07 25](https://github.com/civiform/civiform/assets/2267370/507ab653-75c2-419b-98f7-3c91a9221c8b)

**Comment by bion** [comment] 2023-05-24 16:57
@rasmi the stack trace looks like it may be incomplete, is there more to it further down?

**Comment by rasmi** [comment] 2023-05-24 21:14
That's all I was able to get from CloudWatch, the entries before and after are regular activity (e.g. 

Here are two other stack traces around the same time, unsure if related:
## Error B
```
! @81k9dpmpc - Internal server error, for (GET) [/applicants/50/programs/36/review] ->
```
```
play.api.UnexpectedException: Unexpected exception[NoSuchElementException: No value present]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
	at controllers.ErrorHandler.onServerError(ErrorHandler.java:102)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
```
```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at controllers.applicant.ApplicantProgramReviewController.review(ApplicantProgramReviewController.java:82)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$266(Routes.scala:3533)
	at play.core.routing.HandlerInvokerFactory$$anon$9.resultCall(HandlerInvoker.scala:154)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:119)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:175)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
	at play.api.libs.streams.Accumulator$.$anonfun$futureToSink$1(Accumulator.scala:231)
	at akka.stream.impl.Transform.apply(TraversalBuilder.scala:159)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:522)
```
## Error C

```
[[31merror[0m] p.h.DefaultHttpErrorHandler - 

```
```
! @81k9e13nk - Internal server error, for (POST) [/applicants/50/programs/36/blocks/1/false] ->
```
```
play.api.UnexpectedException: Unexpected exception[RuntimeException: com.jayway.jsonpath.InvalidModificationException: Can only add properties to a map]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
	at controllers.ErrorHandler.onServerError(ErrorHandler.java:102)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
```
```
Caused by: java.lang.RuntimeException: com.jayway.jsonpath.InvalidModificationException: Can only add properties to a map
	at controllers.applicant.ApplicantProgramBlocksController.handleUpdateExceptions(ApplicantProgramBlocksController.java:779)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	... 7 common frames omitted
```
```
Caused by: com.jayway.jsonpath.InvalidModificationException: Can only add properties to a map
	at com.jayway.jsonpath.internal.PathRef$ObjectPropertyPathRef.put(PathRef.java:265)
	at com.jayway.jsonpath.JsonPath.put(JsonPath.java:342)
	at com.jayway.jsonpath.internal.JsonContext.put(JsonContext.java:207)
	at com.jayway.jsonpath.internal.JsonContext.put(JsonContext.java:186)
	at services.CfJsonDocumentContext.putAt(CfJsonDocumentContext.java:286)
	at services.CfJsonDocumentContext.put(CfJsonDocumentContext.java:237)
	at services.CfJsonDocumentContext.putDate(CfJsonDocumentContext.java:137)
	at services.applicant.ApplicantService.stageNormalUpdates(ApplicantService.java:1332)
	at services.applicant.ApplicantService.stageUpdates(ApplicantService.java:1174)
	at services.applicant.ApplicantService.stageAndUpdateIfValid(ApplicantService.java:351)
	at services.applicant.ApplicantService.lambda$stageAndUpdateIfValid$6(ApplicantService.java:324)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
```

**Comment by yotommy** [comment] 2023-07-26 20:22
This appears to be caused by a failure to load the current profile based on the session cookie ([code](https://github.com/civiform/civiform/blob/fe3bc6cf69ff00ce76cecfe414359a3c74238c35/server/app/controllers/applicant/ApplicantProgramReviewController.java#L82)).

**Comment by yotommy** [comment] 2023-07-26 20:24
In a case like this, redirecting to some safe place seems strictly better than throwing an exception.

**Comment by bion** [comment] 2023-07-27 21:56
@yotommy that sounds right to me, at least as an improvement upon the current circumstance.

I'm surprised that these errors would result from an expired session though, e.g. the last one: `Caused by: com.jayway.jsonpath.InvalidModificationException: Can only add properties to a map`

**Comment by yotommy** [comment] 2023-07-28 18:27
I agree, and I suspect these errors have different causes. My description above could account for the stack trace shown in the initial bug comment as well as Error B. Error C looks different. (Note that B & C were included in the bug comment because they were found in the logs around the same time, and the comment says, "[U]nsure if related."

I did spend some time looking at Error C and am including some notes (with no theory of the crime) here:

The exception from the jsonpath `put()` says, "Can only add properties to a map". That exception can be thrown one of two places:

- when [called for a non-repeated path](https://github.com/json-path/JsonPath/blob/21de6207945dfca6b49809fa9dd08c3781b7ab9d/json-path/src/main/java/com/jayway/jsonpath/internal/PathRef.java#L193)
- when [called for a repeated path](https://github.com/json-path/JsonPath/blob/21de6207945dfca6b49809fa9dd08c3781b7ab9d/json-path/src/main/java/com/jayway/jsonpath/internal/PathRef.java#L265)

It appears that the fields are stored in maps, and repeated values are stored in lists. It looks like the exception is thrown if the targeted path does not contain a map (so presumably contains a list).

From the portion of the stack trace in CiviForm code, we called `putAt()`, which is only [called for non-array elements](https://github.com/civiform/civiform/blob/db1c105df48029bf105a0bc4c6d59a3befb03167/server/app/services/CfJsonDocumentContext.java#L237) (i.e., a path that doesn't end in `[n]`).

So it seems like we think we are setting a scalar value, but `JsonPath` finds a list rather than a map when it tries to store the value.

**Comment by rasmi** [comment] 2023-08-03 13:47
These programs were being actively edited around the time of the error (and I believe were in draft form through one or more CiviForm version updates before being published), so this type of mismatch seems plausible.

**Comment by yotommy** [comment] 2023-08-03 14:19
Since program ids are tied to version ids via `versions_programs`, the hypothesis above seems unlikely.

**Comment by yotommy** [comment] 2023-08-04 16:47
Considering the age of this issue, and the recent efforts to enforce consistency, will close this issue. If we observe this again, we can create a new issue.

**Closed** 2023-08-04 18:42 UTC
Labels: bug
