### ISSUE TITLE
Submitting a blank application (when all questions are optional) is throwing an exception

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8499] opened 2024-09-04 20:17 UTC
i don't think this is a northstar issue, but submitting a blank application (when all questions are optional) is throwing an exception

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725469835605869?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Reported by Rocky

**Comment by melanie-exygy** [comment] 2024-09-04 23:11
@rockycodes I'm not able to reproduce, either with the North Star flag on or off.  Are you able to reproduce in staging with the flag off?  @ssandbekkhaug are you able to reproduce this error?

**Comment by rockycodes** [comment] 2024-09-05 15:00
@melanie-exygy yesterday I was getting an error both locally and in staging, but today it's working fine! I'll close this for now and we can re-open if it occurs again.

**Closed by rockycodes** 2024-09-05 15:00 UTC
