### ISSUE TITLE
Allow questions to be deleted

### ISSUE THREAD

**Issue by inghamn** [civiform/civiform#2788] opened 2022-06-23 13:13 UTC
With multiple people working on many programs, questions end up being created but never used.  These can often be entered in error or even duplicates of questions that already existed and used in other programs.

In order to clean up the question bank, it would be nice to permit the deletion of questions that are not used in any programs.

**Comment by cassandralfernandes** [comment] 2022-06-23 17:42
Currently, you can archive questions that are not part of a program but the feature is not intuitive. Cliff, I've added this as an agenda topic to our next Bloomington + Google check in to understand more about your use case and whether or not this issue could be solved with archiving

**Comment by azizova-leyla** [comment] 2022-07-12 15:44
Assigning this to Brett to add indicators to the UI when a question is being in programs, and better messaging about archival options.

**Comment by clouser2** [comment] 2022-07-12 16:23
I plan to start work on this tomorrow. I'll check in with @rahaghas later today to collect feedback on small wins here.

**Comment by clouser2** [comment] 2022-07-12 21:59
Concretely, here's where the archive option shows up: ![Screen Shot 2022-07-12 at 2 49 44 PM](https://user-images.githubusercontent.com/1870301/178601563-f9fcf008-52cb-45f5-9a66-bb0cac0d1a5e.png)

Note that this presently only appears if the question isn't referenced by any active programs. Archiving prevents the question from showing up in the question bank. The CiviForm admin has the option to un-archive one of these questions.

A few hopefully small tweaks we can make to improve the usability here are:
* Split archived questions off into an entirely separate table / section (add a note that these won't be visible in the question bank). As it stands, previously archived questions still show in the list in their previous position. The act of archiving a question warrants putting it below the fold of other questions in my opinion.
* Add another column to the table indicating the number of programs the question is actively used in (which would hopefully make it more apparent why the archive option is not available). Make this a badge with a tooltip listing the programs that the question is referenced by (extra credit)
* Indicate 1) whether the question is archived and 2) number of programs it's referenced by in the page rendered after clicking "View" as well.
* Once the "what programs is this question referenced by" functionality is built out, we could also attempt to surface this in the question bank, though I'm not sure of the best avenue

@rahaghas What do you think about this as a starting point?

**Comment by clouser2** [comment] 2022-07-13 16:10
Confirmed with @rahaghas on the UX side that the plan above seems like a reasonable start.

**Comment by clouser2** [comment] 2022-07-14 18:10
Updates have emerged since my latest plan.

## Text to use for referencing programs counts

Surfacing a count of programs a question is used in is slightly complicated. A few examples:
  * Question is referenced by 4 programs in the active version. Edits are made to remove the question from one of the programs. In this case, the question is referenced by 4 programs in the "published" version and 3 programs in the "draft" version
  * Question is referenced by 4 programs in the active version. New program is created and the question is added. In this case, the question is referenced by 4 programs in the "published" version and 5 programs in the "draft" version.

Due to this, we'll want to use text along the lines of:
```
Referenced in X programs publicly
Referenced in Y programs in the latest draft
```

## Always make the archive option available

Part of the current discoverability problem stems from the fact that the "Archive" option doesn't appear unless there are 0 programs referencing the question. If there are *any* programs referencing the question, the item is hidden.

Surfacing the number of programs referencing a question is a great start, but the feature still won't be discoverable if the user doesn't know they need to update the other referencing programs in order for the option to be displayed.

After some discussion with @rahaghas, we thought we could do something along the lines of:
  * Always display the "Archive" option (unless it's already archived)
  * If 0 programs reference the question, just archive it (current behavior)
  * If N programs reference the question, pop up a modal listing the programs that reference it.
    - Add links that open in new tabs to each program so that the user can delete the reference
  * Once the user has deleted the reference, they can confirm the dialog and the question can be archived

This requires a few server-side changes:
  * Make sure that the current archive controller will throw an error if programs still reference the question. Redirect to the questions view and flash an error message indicating that programs still reference it
  * If we want to deep-link to the "Program builder" screen that references the question, we may need to create draft versions of a program in order to make the edit. We might need a new handler for this

This should make the feature a bit more discoverable and usable. We could even consider automatically deleting the question from program versions if it was deemed "safe" (e.g. only question shown on a screen), but that would require more thought and there'd likely be a lot of edge cases we need to consider.

## Switch UI layout to be consistent with mocks in Figma

The set of actions displayed can tend to be a wall of links and could likely benefit from updating to a design consistent with our program index view. Assuming it's not too much work, we could make this update as a follow-on to the other work.

**Comment by clouser2** [comment] 2022-07-14 18:13
I'm going to start with the "Always make the archive option available" stream from the above comment since I think it has the highest usability impact. Building that out will then make adding the "reference in X programs" count pretty trivial.

**Comment by clouser2** [comment] 2022-08-15 19:38
The proposal has been implemented. For now, I've left out the ability to see and restore previously archived questions from older program versions. If we have a strong reason to introduce that, we can certainly add later. It felt an unnecessary DB query to support it for now if we haven't received feedback for it's need.

**Closed** 2022-08-15 20:18 UTC
Labels: feature, admin-ui
