### ISSUE TITLE
"Create an account or sign in" modal is not centered

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8500] opened 2024-09-04 20:19 UTC
From the application submission confirmation page, when you click "Back to homepage" as a guest, on tablet, the "Create an account or sign in" modal is not centered [vertically]:

Browser:  Firefox (not reproducible on Chrome)
Device size:  tablet (810 x 1080)

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725470128394759?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Reported by Melanie

![Image](https://github.com/user-attachments/assets/91dd87c7-ef26-4abd-a566-a03900cae1da)

**Comment by ssandbekkhaug** [comment] 2024-09-18 19:48
@melanie-exygy Do you have more specific instructions to repro? I've tried on Chrome and Safari with different window sizes and I can't repro

**Comment by melanie-exygy** [comment] 2024-09-18 22:31
> @melanie-exygy Do you have more specific instructions to repro? I've tried on Chrome and Safari with different window sizes and I can't repro

@ssandbekkhaug, I can only reproduce in Firefox on tablet.  I added that to the issue description.  Also, I'm testing in the Firefox dev tools.  I don't have a tablet, so can't test there unfortunately.

**Comment by ssandbekkhaug** [comment] 2024-09-25 16:58
I tried in Firefox and still can't repro. Can we do a quick pairing session and figure out how to repro together?

<img width="807" alt="Screenshot 2024-09-25 at 11 57 54 AM" src="https://github.com/user-attachments/assets/ef32a03f-6cb6-4fd1-91e2-0a79298aee53">

**Comment by melanie-exygy** [comment] 2024-09-25 21:49
@ssandbekkhaug I think I've figured out that the problem was that Firefox dev tools doesn't show the entire page in the viewport.  When I scroll down, it looks like the modal is correctly centered.  Closing this bug.

**Closed by melanie-exygy** 2024-09-25 21:49 UTC
Labels: [Epic] North Star Applicant UI, triaged
